name: mpv
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Run custom command before building'
        required: false
        type: string
      github_release:
        description: 'Upload to Github release'
        required: false
        default: true
        type: boolean
      mpv_tarball:
        description: 'Build latest mpv tarball'
        required: false
        default: false
        type: boolean

jobs:
  build_mpv:
    name: Building mpv
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bit: [32, 64, 64-v3]
    env:
      BIT: ${{ matrix.bit }}
    container:
      image: docker://ghcr.io/shinchiro/archlinux:latest
    outputs:
      mpv_ver: ${{ steps.build_mpv_step.outputs.mpv_ver }}
    steps:
      - name: Init variable
        run: |
          if [[ $BIT == 32 ]]; then
            echo "arch=i686" >> $GITHUB_ENV
          elif [[ $BIT == 64 ]]; then
            echo "arch=x86_64" >> $GITHUB_ENV
          elif [[ $BIT == 64-v3 ]]; then
            echo "arch=x86_64" >> $GITHUB_ENV
            echo "gcc_arch=-DGCC_ARCH=x86-64-v3" >> $GITHUB_ENV
            echo "x86_64_level=-v3" >> $GITHUB_ENV
          fi

      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main
        with:
          ref: main

      - name: Loading build${{ matrix.bit }} cache
        uses: actions/cache/restore@main
        with:
          path: build${{ matrix.bit }}
          key: ${{ secrets.CACHE_VERSION }}-build${{ matrix.bit }}-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-build${{ matrix.bit }}

      - name: Loading repository cache
        uses: actions/cache/restore@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}
          restore-keys: |
            ${{ secrets.CACHE_VERSION }}-repository

      - name: Running custom command
        if: ${{ github.event.inputs.command != '' }}
        continue-on-error: true
        run: ${{ github.event.inputs.command }}

      - name: Downloading source
        run: |
          cmake --version
          cmake -DTARGET_ARCH=${{ env.arch }}-w64-mingw32 ${{ env.gcc_arch }} -DALWAYS_REMOVE_BUILDFILES=ON -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -G Ninja -Bbuild$BIT -H.
          ninja -C build$BIT download || true

      - name: Building toolchain
        run: |
          if [[ ! "$(ls -A build$BIT/install/bin/${{ env.arch }}-w64-mingw32-gcc)" ]]; then ninja -C build$BIT gcc; fi

      - name: Building mpv
        id: build_mpv_step
        env:
          MPV_TARBALL: ${{ github.event.inputs.mpv_tarball }}
        run: |
          ninja -C build$BIT update
          $MPV_TARBALL && ninja -C build$BIT mpv-release || ninja -C build$BIT mpv
          $MPV_TARBALL && echo "mpv_ver=$(cat $PWD/src_packages/mpv-release/VERSION)" >> $GITHUB_OUTPUT || echo "mpv_ver=$(cat build$BIT/install/mingw/mpv-version.h | grep -oP '#define VERSION "(\K[^"]+)')" >> $GITHUB_OUTPUT

      - name: Packaging mpv
        run: |
          mkdir -p release$BIT
          rm -rf build$BIT/mpv-debug*; ninja -C build$BIT mpv-packaging; mv build$BIT/mpv*.7z release$BIT

      - name: Copying ffmpeg
        run: |
          hash=$(git -C src_packages/ffmpeg rev-parse --short HEAD)
          7z a -m0=lzma2 -mx=9 -ms=on release$BIT/ffmpeg-${{ env.arch }}${{ env.x86_64_level }}-git-$hash.7z ./build$BIT/install/mingw/bin/ffmpeg.exe

      - name: Print dir info
        id: print_dir_info
        continue-on-error: true
        run: |
          ls -alh build$BIT/install build$BIT/install/*/ build$BIT/install/lib/*/ build$BIT/install/mingw/lib build$BIT/install/mingw/lib/*/

      - name: Collecting logs
        run: |
          mkdir -p build${BIT}_logs
          cp -fr $(find build$BIT -type f -iname "*-*.log" -or -wholename "*/ffbuild/config.log") build${BIT}_logs || true
          7z a -m0=lzma2 -mx=9 -ms=on logs.7z build*logs

      - name: Uploading logs
        continue-on-error: true
        uses: actions/upload-artifact@master
        with:
          name: logs_${{ matrix.bit }}
          path: logs.7z
          retention-days: 1

      - name: Uploading artifact
        id: upload_artifact
        continue-on-error: true
        uses: actions/upload-artifact@master
        with:
          name: release_${{ matrix.bit }}
          path: release${{ matrix.bit }}/*.7z
          retention-days: 1

      - name: Cleaning build directory
        if: always()
        run: |
          rm -rf build$BIT/mpv*

      - name: Saving build${{ matrix.bit }} cache
        uses: actions/cache/save@main
        if: ${{ success() }}
        with:
          path: build${{ matrix.bit }}
          key: ${{ secrets.CACHE_VERSION }}-build${{ matrix.bit }}-${{ github.run_id }}

      - name: Saving repository cache
        uses: actions/cache/save@main
        if: ${{ success() && matrix.bit == '32' }}
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}

      - name: Saving release${{ matrix.bit }} cache
        uses: actions/cache/save@main
        with:
          path: release${{ matrix.bit }}
          key: ${{ secrets.CACHE_VERSION }}-release${{ matrix.bit }}-${{ github.run_id }}

  release:
    name: Upload releases
    runs-on: ubuntu-latest
    needs: build_mpv
    env:
      release32_key: ${{ secrets.CACHE_VERSION }}-release32-${{ github.run_id }}
      release64_key: ${{ secrets.CACHE_VERSION }}-release64-${{ github.run_id }}
      release64_v3_key: ${{ secrets.CACHE_VERSION }}-release64-v3-${{ github.run_id }}
    container:
      image: docker://alpine:latest

    steps:
      - name: Installing dependencies
        shell: sh
        run: |
          apk add --update --no-cache bash git file openssh curl tar zstd jq
          git config --global pull.rebase true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main
        with:
          ref: master

      - name: Loading release32 cache
        uses: actions/cache/restore@main
        with:
          path: release32
          key: ${{ env.release32_key }}

      - name: Loading release64 cache
        uses: actions/cache/restore@main
        with:
          path: release64
          key: ${{ env.release64_key }}

      - name: Loading release64-v3 cache
        uses: actions/cache/restore@main
        with:
          path: release64-v3
          key: ${{ env.release64_v3_key }}

      - name: Moving archives
        run: |
          mkdir -p release
          mv release32/* release64/* release64-v3/* release
          du -ah release/*
          echo "short_date=$(date "+%Y%m%d")" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.github_release == 'true' }}
        continue-on-error: true
        with:
          prerelease: true
          tag_name: ${{ needs.build_mpv.outputs.mpv_ver }}-${{ env.short_date }}
          fail_on_unmatched_files: true
          files: release/*
